taskotimer_site/taskotimer_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  path('tasks/', include('tasks.urls')),
  path('admin/', admin.site.urls),
]

taskotimer_site/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('/new', views.new, name='new'),
]

taskotimer_site/tasks/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    created = models.DateTimeField('date created')
    due_to = models.DateTimeField('due to date')
    status = models.CharField(max_length=50)
    category = models.CharField(max_length=100)
    completness = models.IntegerField(default=0)

    def __str__(self):
        return ("name is: %s, description: %s" % (self.name, self.description))

taskotimer_site/tasks/views.py
from django.shortcuts import render, get_object_or_404
# from django.http import HttpResponse
from tasks.models import Task

# Create your views here.


def index(request):
    tasks = Task.objects.all()
    return render(request, 'tasks/index.html', {'tasks': tasks})


def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    return render(request, 'tasks/details.html', {'task': task})


def new(request):
    return render(request, 'tasks/new.html')

taskotimer_site/tasks/templates/tasks/details.html
{% if task %}
<h1> Task {{ task.name }}</h1>
<p> some shitty shit </p>
{% endif %}

taskotimer_site/tasks/templates/tasks/index.html
<head>
  <title>Shit!</title>
</head>
<body>
  <style type="text/css">
    div.individual_task > div {
      display: inline;
    }

    div.create_task {
      background: 'dedede';
    }

  </style>

{% if tasks %}
<h1 class="task_list"> Task list </h1>
	<div class="task_container">
	{% for task in tasks %}
      <div class="individual_task">
      	<div class="name">{{ task.name }}</div>
      	<div class="description">{{ task.description }}</div>
      	<div class="created">{{ task.created }}</div>
      	<div class="status">{{ task.status }}</div>
      	<div class="category">{{ task.category }}</div>
      	<div class="completness">{{ task.completness }}</div>
        <div class="link2task"><a href="{% url 'tasks:detail' task.id %}">link_to_task</div>
      </div>
      <div class="create_task"><a href="{% url 'tasks:new' %}">Create new task</div>
	{% endfor %}
    </div>
{% endif %}
</body>

taskotimer_site/tasks/templates/tasks/new.html
<h1>Create taske</h1>
<p> here goes code. blah blah blah </p>